import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import {
  READER_FILES,
  readerDest,
  resolveConfigRoot,
  syncConfigReaders,
} from './sync-config-readers.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

test('the six typed Readers are auto-generated and are not hand-edited', () => {
  for (const [side, name] of READER_FILES) {
    const text = readFileSync(readerDest(ROOT, side, name), 'utf8');
    assert.match(text, /<auto-generated>/);
    assert.match(text, /生成物不得手改/);
    assert.match(text, /export --csharp-out/);
    assert.doesNotMatch(text, /hand[- ]edit/i);
  }
});

test('re-running LumioConfig export --csharp-out leaves the six Readers byte-identical', () => {
  const configRoot = resolveConfigRoot({ repoRoot: ROOT });
  assert.ok(
    configRoot,
    'LUMIO_CONFIG_ROOT or sibling LumioConfig is required so this test can drive the real generator',
  );
  const result = syncConfigReaders({ repoRoot: ROOT, checkOnly: true });
  assert.equal(result.status, 'OK');
  assert.equal(result.checkOnly, true);
  assert.equal(result.files, 6);
});
